language:
  - ruby
  - java
jdk: openjdk8  
rvm:
  - 2.5.0

before_install:
  - gem update --system
  - gem install bundler:1.17.3

install:
  - bundle install
  - gem install s3_website

branches:
  only:
    - master

notifications:
  email:
    recipients:
      - deploy@theqrl.org
    on_success: always
    on_failure: always

script:
  - chmod +x _scripts/build.sh
  - _scripts/build.sh

after_success:
  - chmod +x _scripts/deploy.sh
  - _scripts/deploy.sh
